### ISSUE TITLE
Can't install using `pod VectorArithmetic`

### ISSUE THREAD

**Issue by kzaher** [seivan/VectorArithmetic#5]
Hi @seivan ,

Did you maybe push this to CocoaPods main repo?

https://cocoapods.org/?q=VectorArithmetic

Maybe you just need to say `pod trunk push VectorArithmetic.podspec`.

Unsure why `pod VectorArithmetic` doesn't work.

```
[!] Unable to find a specification for `VectorArithmetic`
```

¯\\\_(ツ)\_/¯

**Comment by seivan** [comment]
@kzaher Because I haven't pushed it, as you suspected. I'll get on it now, but...

I'm slowly leaving Cocoapods, after ~15 pods published, I am starting to see the downside. Recently I've started working with a closed framework and It hasn't been the smoothest of all rides. Everything from consuming the framework, to building it, to using it with tests and sample applications.

We're going to distribute using Cocoapods, but without using the trunk or private spec repo, instead we'll rely on git tags, so we can support Carthage as well.

**Comment by seivan** [comment]
@kzaher It should be pushed now. Not sure if it works as I can't run the tests as of now. Let me know if there is anything else I can do.

**Comment by seivan** [comment]
@kzaher Version 1.3.1 is now pushed on Pod trunks. 

I strongly recommend using submodules and subproject as the xcode project itself builds a framework, or using carthage linked to this repo and its git tag.

Carthage will build an OSX and iOS framework for you to use.

**Comment by seivan** [comment]
@kzaher Version 1.3.2 is now pushed on Pod trunks. 

I strongly recommend using submodules and subproject as the xcode project itself builds a framework, or using carthage linked to this repo and its git tag.

Carthage will build an OSX and iOS framework for you to use.
